title: گربه قرمز
description: وبلاگ امنیت سایبری | دارک‌وب، بدافزار، باج‌افزار و دفاع
url: "https://RedCat-2026.github.io"
baseurl: ""

lang: fa
direction: rtl
timezone: Asia/Tehran

remote_theme: cotes2020/jekyll-theme-chirpy

# تنظیمات Chirpy
paginate: 5

author:
  name: گربه قرمز
  bio: "کاوش در دنیای تاریک امنیت سایبری"
