title: گربه قرمز
description: کاوش در دنیای کامپیوتر ، اینترنت ، هوش مصنوعی و امنیت سایبری
url: "https://RedCat-2026.github.io"
baseurl: ""   # برای user site خالی بذار

lang: fa
timezone: Asia/Tehran

author:
  name: گربه قرمز
  bio:    " مقالات تحلیلی در زمینه کامپیوتر"
